### ISSUE TITLE
uniapp在小程序中生成css重复

### ISSUE THREAD

**Issue by nyrf** [forsigner/fower#12]
如果一个页面有两个使用同样类的`view`，会出现这种情况，比如

```vue
    <view bgBlue500 w-750>
      bgBlue500 p20
    </view>

    <view bgBlue500 w-375>
      bgBlue500 p20
    </view>
```
```css
.bgBlue500 {
  background-color: #339af0;
}
.w-375 {
  width: 375rpx;
}
.dark .bgBlue400--dark {
  background-color: #4dabf7;
}
.bgBlue500 {
  background-color: #339af0;
}
.w-750 {
  width: 750rpx;
}
.dark .bgBlue400--dark {
  background-color: #4dabf7;
}
```

可以看到生成的`bgBlue500 `有两个，而且还生成了dark的样式？
